"""
Django settings for italy project.

Generated by 'django-admin startproject' using Django 3.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv   #for python-dotenv method
load_dotenv()                    #for python-dotenv method
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^c&relkqp$p$s5(hf#d5*)zah6ah)5xdtj^&74%k1+_e81_lwx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['192.168.1.202', 'italy.local']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_celery_results',
    'import_export',
    'crispy_forms',
    'celery_progress',
    'home',
    'login',
    'Orders',
    'Basket',
    'Machines',
    'Spareparts',
    'warehouse',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'italy.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'italy.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'databases/italy/italia.db',
    },
    'SparePartsDb': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'databases/warehouse/3. ΚΑΙΝΟΥΡΙΑ_ΑΠΟΘΗΚΗ.db',

    }
}
DATABASE_ROUTERS = ['warehouse.router.WarehouseRouter']

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'el-GR'

TIME_ZONE = 'Europe/Athens'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, "static/")
STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# https://docs.djangoproject.com/en/3.0/topics/auth/default/#the-login-required-decorator
LOGIN_URL = 'login:login'


CRISPY_TEMPLATE_PACK = 'bootstrap4'


# https://docs.djangoproject.com/en/3.0/ref/settings/#std:setting-SESSION_ENGINE
CSRF_COOKIE_DOMAIN = '127.0.0.1'

#  If this is set to True, client-side JavaScript will not be able to access the session cookie.
SESSION_COOKIE_HTTPONLY = True

SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 600  # 10 Min
SESSION_SAVE_EVERY_REQUEST = True

# If this is set to True, the cookie will be marked as “secure”,
#  which means browsers may ensure that the cookie is only sent under an HTTPS connecion
SESSION_COOKIE_SECURE = False

CSRF_COOKIE_HTTPONLY = True
CSRF_USE_SESSIONS = True
SECURE_SSL_REDIRECT = False
SESSION_ENGINE = "django.contrib.sessions.backends.db"
LOGIN_REDIRECT_URL = '/home/'

DATE_INPUT_FORMATS = ['%d.%m.%Y']

# Italy and Info-Copy Login
CREDENTIALS = os.path.join(BASE_DIR, "credentials.yml")

# ------------- CELERY -----------------
CELERY_USER = os.environ.get('CELERY_USER')
CELERY_USER_PASS = os.environ.get('CELERY_USER_PASS')
CELERY_BROKER_URL = f"amqp://{CELERY_USER}:{CELERY_USER_PASS}@localhost:5672/italy.local"
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_BACKEND = 'django-db'



