# Generated by Django 3.2.4 on 2021-06-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BROTHER',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('PARTS_NR', models.CharField(blank=True, db_column='PARTS_NR', max_length=50, null=True)),
                ('ΠΕΡΙΓΡΑΦΗ', models.TextField(blank=True, db_column='ΠΕΡΙΓΡΑΦΗ', null=True)),
                ('ΚΩΔΙΚΟΣ', models.CharField(blank=True, db_column='ΚΩΔΙΚΟΣ', max_length=50, null=True)),
                ('ΤΕΜΑΧΙΑ', models.CharField(blank=True, db_column='ΤΕΜΑΧΙΑ', max_length=50, null=True)),
                ('ΠΑΡΑΤΗΡΗΣΗΣ', models.TextField(blank=True, db_column='ΠΑΡΑΤΗΡΗΣΗΣ', null=True)),
            ],
            options={
                'db_table': 'BROTHER',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CANON',
            fields=[
                ('ID', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('PARTS_NR', models.CharField(blank=True, db_column='PARTS_NR', max_length=50, null=True)),
                ('ΠΕΡΙΓΡΑΦΗ', models.TextField(blank=True, db_column='ΠΕΡΙΓΡΑΦΗ', null=True)),
                ('ΚΩΔΙΚΟΣ', models.CharField(blank=True, db_column='ΚΩΔΙΚΟΣ', max_length=50, null=True)),
                ('ΤΕΜΑΧΙΑ', models.CharField(blank=True, db_column='ΤΕΜΑΧΙΑ', max_length=50, null=True)),
                ('ΠΑΡΑΤΗΡΗΣΗΣ', models.TextField(blank=True, db_column='ΠΑΡΑΤΗΡΗΣΗΣ', null=True)),
            ],
            options={
                'db_table': 'CANON',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EPSON',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('PARTS_NR', models.CharField(blank=True, db_column='PARTS_NR', max_length=50, null=True)),
                ('ΠΕΡΙΓΡΑΦΗ', models.TextField(blank=True, db_column='ΠΕΡΙΓΡΑΦΗ', null=True)),
                ('ΚΩΔΙΚΟΣ', models.CharField(blank=True, db_column='ΚΩΔΙΚΟΣ', max_length=50, null=True)),
                ('ΤΕΜΑΧΙΑ', models.CharField(blank=True, db_column='ΤΕΜΑΧΙΑ', max_length=50, null=True)),
                ('ΠΑΡΑΤΗΡΗΣΗΣ', models.TextField(blank=True, db_column='ΠΑΡΑΤΗΡΗΣΗΣ', null=True)),
            ],
            options={
                'db_table': 'EPSON',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KONICA',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('PARTS_NR', models.CharField(blank=True, db_column='PARTS_NR', max_length=50, null=True)),
                ('ΠΕΡΙΓΡΑΦΗ', models.TextField(blank=True, db_column='ΠΕΡΙΓΡΑΦΗ', null=True)),
                ('ΚΩΔΙΚΟΣ', models.CharField(blank=True, db_column='ΚΩΔΙΚΟΣ', max_length=50, null=True)),
                ('ΤΕΜΑΧΙΑ', models.CharField(blank=True, db_column='ΤΕΜΑΧΙΑ', max_length=50, null=True)),
                ('ΠΑΡΑΤΗΡΗΣΗΣ', models.TextField(blank=True, db_column='ΠΑΡΑΤΗΡΗΣΗΣ', null=True)),
            ],
            options={
                'db_table': 'KONICA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KYOCERA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PARTS_NR', models.CharField(blank=True, db_column='PARTS_NR', max_length=50, null=True)),
                ('ΠΕΡΙΓΡΑΦΗ', models.TextField(blank=True, db_column='ΠΕΡΙΓΡΑΦΗ', null=True)),
                ('ΚΩΔΙΚΟΣ', models.CharField(blank=True, db_column='ΚΩΔΙΚΟΣ', max_length=50, null=True)),
                ('ΤΕΜΑΧΙΑ', models.CharField(blank=True, db_column='ΤΕΜΑΧΙΑ', max_length=50, null=True)),
                ('ΠΑΡΑΤΗΡΗΣΗΣ', models.TextField(blank=True, db_column='ΠΑΡΑΤΗΡΗΣΗΣ', null=True)),
            ],
            options={
                'db_table': 'KYOCERA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LEXMARK',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('PARTS_NR', models.CharField(blank=True, db_column='PARTS_NR', max_length=50, null=True)),
                ('ΠΕΡΙΓΡΑΦΗ', models.TextField(blank=True, db_column='ΠΕΡΙΓΡΑΦΗ', null=True)),
                ('ΚΩΔΙΚΟΣ', models.CharField(blank=True, db_column='ΚΩΔΙΚΟΣ', max_length=50, null=True)),
                ('ΤΕΜΑΧΙΑ', models.CharField(blank=True, db_column='ΤΕΜΑΧΙΑ', max_length=50, null=True)),
                ('ΠΑΡΑΤΗΡΗΣΗΣ', models.TextField(blank=True, db_column='ΠΑΡΑΤΗΡΗΣΗΣ', null=True)),
            ],
            options={
                'db_table': 'LEXMARK',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OKI',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('PARTS_NR', models.CharField(blank=True, db_column='PARTS_NR', max_length=50, null=True)),
                ('ΠΕΡΙΓΡΑΦΗ', models.TextField(blank=True, db_column='ΠΕΡΙΓΡΑΦΗ', null=True)),
                ('ΚΩΔΙΚΟΣ', models.CharField(blank=True, db_column='ΚΩΔΙΚΟΣ', max_length=50, null=True)),
                ('ΤΕΜΑΧΙΑ', models.CharField(blank=True, db_column='ΤΕΜΑΧΙΑ', max_length=50, null=True)),
                ('ΠΑΡΑΤΗΡΗΣΗΣ', models.TextField(blank=True, db_column='ΠΑΡΑΤΗΡΗΣΗΣ', null=True)),
            ],
            options={
                'db_table': 'OKI',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RICOH',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('PARTS_NR', models.CharField(blank=True, db_column='PARTS_NR', max_length=50, null=True)),
                ('ΠΕΡΙΓΡΑΦΗ', models.TextField(blank=True, db_column='ΠΕΡΙΓΡΑΦΗ', null=True)),
                ('ΚΩΔΙΚΟΣ', models.CharField(blank=True, db_column='ΚΩΔΙΚΟΣ', max_length=50, null=True)),
                ('ΤΕΜΑΧΙΑ', models.CharField(blank=True, db_column='ΤΕΜΑΧΙΑ', max_length=50, null=True)),
                ('ΠΑΡΑΤΗΡΗΣΗΣ', models.TextField(blank=True, db_column='ΠΑΡΑΤΗΡΗΣΗΣ', null=True)),
            ],
            options={
                'db_table': 'RICOH',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SAMSUNG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PARTS_NR', models.CharField(blank=True, db_column='PARTS_NR', max_length=50, null=True)),
                ('ΠΕΡΙΓΡΑΦΗ', models.TextField(blank=True, db_column='ΠΕΡΙΓΡΑΦΗ', null=True)),
                ('ΚΩΔΙΚΟΣ', models.CharField(blank=True, db_column='ΚΩΔΙΚΟΣ', max_length=50, null=True)),
                ('ΤΕΜΑΧΙΑ', models.CharField(blank=True, db_column='ΤΕΜΑΧΙΑ', max_length=50, null=True)),
                ('ΠΑΡΑΤΗΡΗΣΗΣ', models.TextField(blank=True, db_column='ΠΑΡΑΤΗΡΗΣΗΣ', null=True)),
            ],
            options={
                'db_table': 'SAMSUNG',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SHARP',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('PARTS_NR', models.CharField(blank=True, db_column='PARTS_NR', max_length=50, null=True)),
                ('ΠΕΡΙΓΡΑΦΗ', models.TextField(blank=True, db_column='ΠΕΡΙΓΡΑΦΗ', null=True)),
                ('ΚΩΔΙΚΟΣ', models.CharField(blank=True, db_column='ΚΩΔΙΚΟΣ', max_length=50, null=True)),
                ('ΤΕΜΑΧΙΑ', models.CharField(blank=True, db_column='ΤΕΜΑΧΙΑ', max_length=50, null=True)),
                ('ΠΑΡΑΤΗΡΗΣΗΣ', models.TextField(blank=True, db_column='ΠΑΡΑΤΗΡΗΣΗΣ', null=True)),
            ],
            options={
                'db_table': 'SHARP',
                'managed': False,
            },
        ),
    ]
